// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var BEValidator = require("./BEValidator.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

function app() {
  return ReasonReact.element(/* None */0, /* None */0, BEValidator.make(/* array */[]));
}

exports.app = app;
/* BEValidator Not a pure module */
