// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var TextInput$BsReactNative = require("bs-react-native/lib/js/src/components/textInput.js");
var StyleSheet$BsReactNative = require("bs-react-native/lib/js/src/styleSheet.js");

var component = ReasonReact.statelessComponent("BEInput");

var placeholder = "INPUT YOUR SENTENCES HERE!!";

var styles = StyleSheet$BsReactNative.create({
      view: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.flex(5),
            /* :: */[
              Style$BsReactNative.justifyContent(/* FlexEnd */1),
              /* :: */[
                Style$BsReactNative.width(/* Pct */Block.__(1, [100])),
                /* [] */0
              ]
            ]
          ]),
      input: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.margin(/* Pt */Block.__(0, [10])),
            /* :: */[
              Style$BsReactNative.padding(/* Pt */Block.__(0, [10])),
              /* [] */0
            ]
          ])
    });

function make(onChangeText, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, View$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[styles.view], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, TextInput$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[styles.input], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[/* true */1], /* None */0, /* None */0, /* Some */[onChangeText], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[placeholder], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[]))]));
    });
  return newrecord;
}

var multiline = /* true */1;

exports.component = component;
exports.multiline = multiline;
exports.placeholder = placeholder;
exports.styles = styles;
exports.make = make;
/* component Not a pure module */
