// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var ReactNative = require("react-native");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var Button$BsReactNative = require("bs-react-native/lib/js/src/components/button.js");

var component = ReasonReact.statelessComponent("TranslationButton");

var url = "https://translate.google.com/#en/ja/";

function onPress(text) {
  ReactNative.Linking.openURL(url + encodeURIComponent(text));
  return /* () */0;
}

var title = "翻訳する";

var style = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.margin(/* Pt */Block.__(0, [10])),
      /* :: */[
        Style$BsReactNative.flex(4),
        /* [] */0
      ]
    ]);

function make(text, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, View$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[style], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, Button$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* Some */[(function () {
                                      return onPress(text);
                                    })], /* None */0, /* Some */[title])(/* array */[]))]));
    });
  return newrecord;
}

exports.component = component;
exports.url = url;
exports.onPress = onPress;
exports.title = title;
exports.style = style;
exports.make = make;
/* component Not a pure module */
